import org.springframework.boot.gradle.plugin.SpringBootPlugin

plugins {
    id 'bio.terra.policy.java-library-conventions'
    id 'maven-publish'
    id 'io.spring.dependency-management'
    id 'org.hidetake.swagger.generator'
    // See https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/issues/106
    // for the artifactregistry version
    id 'com.google.cloud.artifactregistry.gradle-plugin' version '2.2.3'
}

dependencyManagement {
    imports {
        mavenBom(SpringBootPlugin.BOM_COORDINATES)
    }
}

apply from: 'publishing.gradle'
apply from: 'swagger.gradle'

dependencies {
    implementation('org.yaml:snakeyaml') {
        version {
            strictly('2.0')
        }
    }
}
