version: "3.3"
services:
  db:
    build:
      dockerfile: ./docker/db.Dockerfile
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./docker/db.env
